signal: MW_B2
period: 2023-01-01~2026-06-22
total_trades: 106741
by_hold_days:
  H5:
    win_rate: 0.3397
    win_rate_js: 0.3397
    mean_ret: -1.51
    median_ret: -3.52
    profit_loss_ratio: 1.35
    kelly: 0.0
    samples: 5219
  H10:
    win_rate: 0.3581
    win_rate_js: 0.3581
    mean_ret: -1.02
    median_ret: -3.59
    profit_loss_ratio: 1.48
    kelly: 0.0
    samples: 5228
  H20:
    win_rate: 0.3619
    win_rate_js: 0.3619
    mean_ret: -1.2
    median_ret: -4.72
    profit_loss_ratio: 1.49
    kelly: 0.0
    samples: 5228
  H60:
    win_rate: 0.3809
    win_rate_js: 0.3809
    mean_ret: 0.09
    median_ret: -6.34
    profit_loss_ratio: 1.64
    kelly: 0.0032
    samples: 5088
by_entry_method:
  T+0_C:
    win_rate: 0.3619
    mean_ret: -1.2
    samples: 5228
  T+1_O:
    win_rate: 0.3546
    mean_ret: -1.53
    samples: 5212
  T+2_O:
    win_rate: 0.3473
    mean_ret: -1.84
    samples: 5206
