f = open("D:/hanako/investment-system/src/scanners/pocket_pivot_v2.py", "r", encoding="utf-8")
t = f.read(); f.close()
t = t.replace("sma50", "sma60")
t = t.replace("ma50", "ma60")
t = t.replace("'min_l_distance': 10", "'min_l_distance': 5")
t = t.replace("'base_depth_min': 0.08", "")  # remove unused
t = t.replace("'base_depth_max': 0.40", "")
f = open("D:/hanako/investment-system/src/scanners/pocket_pivot_v2.py", "w", encoding="utf-8")
f.write(t); f.close()
print("done")
