import sqlite3
c=sqlite3.connect("D:/hanako/investment-system/data/lixinger.db")
cur=c.cursor()
cur.execute("SELECT score_i2,COUNT(*) FROM mw_signal_daily GROUP BY score_i2 ORDER BY score_i2 DESC")
print("score_i2:", cur.fetchall())
cur.execute("SELECT score_d,COUNT(*) FROM mw_signal_daily GROUP BY score_d ORDER BY score_d DESC")
print("score_d:", cur.fetchall())
cur.execute("SELECT confidence,COUNT(*) FROM mw_signal_daily GROUP BY confidence")
print("conf:", cur.fetchall())
cur.execute("SELECT COUNT(*),AVG(score),MAX(score) FROM mw_signal_daily")
print("score stats:", cur.fetchone())
cur.execute("SELECT COUNT(*) FROM mw_signal_daily WHERE is_plus=1")
print("PLUS:", cur.fetchone()[0])
c.close()
